Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  def configure_client(config, name, ip, memory, script_path)
    config.vm.define name do |client|
      client.vm.box = "eurolinux-vagrant/centos-stream-9"
      client.vm.box_version = "9.0.43"
      client.vm.hostname = name
      client.vm.network "private_network", ip: ip
      client.vm.provider "virtualbox" do |vb|
        vb.memory = memory
      end

      client.vm.provision "shell", path: "scripts/#{script_path}", privileged: true
      client.vm.provision "shell", path: "scripts/nrpe_centos.sh", privileged: true
    end
  end

  configure_client(config, "db01", "192.168.56.15", 600, "db_provision.sh")
  configure_client(config, "mc01", "192.168.56.14", 600, "mc_provision.sh")
  configure_client(config, "rmq01", "192.168.56.13", 600, "rmq_provision.sh")
  configure_client(config, "app01", "192.168.56.12", 800, "app_provision.sh")

  ### Nginx VM (Ubuntu) ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.11"

    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "800"
      vb.gui = false
    end
    web01.vm.boot_timeout = 1000

    web01.vm.provision "shell", path: "scripts/web_provision.sh"
  end

  ### Nagios VM ###
  config.vm.define "nagios" do |nagios|
    nagios.vm.box = "eurolinux-vagrant/centos-stream-9"
    nagios.vm.box_version = "9.0.43"
    nagios.vm.hostname = "nagios"
    nagios.vm.network "private_network", ip: "192.168.56.10"

    nagios.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    nagios.vm.provision "shell", path: "scripts/nagios_provision.sh", privileged: true
  end
end
